"""Physical-coordinate instrument responses for spectral and angular detector bins.

This is device-dependent code, not physics. It holds both the value objects describing
*this* detector's response and the routines that apply it, because those two belong to
the same pipeline stage -- sibling stages (aperture weighting, notch filters, pixel
reduction) get their own modules alongside this one.

Nothing here may import from the data or orchestration layers (``tsadar.data``,
``tsadar.inverse``, ``tsadar.forward``, ``tsadar.runner``) or read a config dict.
Translating an input deck into these value objects is the caller's job, so that porting
TSADAR to a new diagnostic means constructing them directly rather than mimicking
OMEGA's nested deck layout to reach a constructor.
"""

from dataclasses import dataclass
from typing import Tuple

import numpy as np
from jax import vmap
from jax import numpy as jnp
from jax.scipy.special import ndtr
from jax.scipy.signal import fftconvolve


def _bin_edges_from_centers(axis):
    """Infer finite physical-coordinate cells around ordered sample centers."""

    axis = jnp.ravel(jnp.asarray(axis))
    if axis.size < 2:
        raise ValueError("At least two coordinate centers are required for a Gaussian IRF")
    spacing = jnp.diff(axis)
    return jnp.concatenate(
        (
            axis[:1] - 0.5 * spacing[:1],
            axis[:-1] + 0.5 * spacing,
            axis[-1:] + 0.5 * spacing[-1:],
        )
    )


def _normal_cdf_antiderivative(z):
    """Return an antiderivative of the standard-normal CDF."""

    density = jnp.exp(-0.5 * z**2) / jnp.sqrt(2.0 * jnp.pi)
    return z * ndtr(z) + density


def _gaussian_bin_response(axis, stddev):
    r"""Map physical-coordinate source-bin means to blurred output-bin means.

    For inferred source/output edges :math:`x_j` and :math:`y_i`, this returns

    .. math::

       R_{ij} = \frac{1}{\Delta y_i}
          \int_{y_i}^{y_{i+1}}\int_{x_j}^{x_{j+1}}
          G_\sigma(y-x)\,dx\,dy.

    The double integral is evaluated analytically with the antiderivative of the
    normal CDF. Unlike an index convolution, this is centered and unit-area on an
    even or nonuniform calibrated axis. A single-bin axis has no resolvable blur and
    maps identically.
    """

    if stddev <= 0:
        raise ValueError(f"Gaussian standard deviation must be positive, got {stddev!r}.")

    axis = jnp.ravel(jnp.asarray(axis))
    if axis.size == 1:
        return jnp.ones((1, 1), dtype=axis.dtype)

    edges = _bin_edges_from_centers(axis)
    output_lower = edges[:-1, None]
    output_upper = edges[1:, None]
    source_lower = edges[None, :-1]
    source_upper = edges[None, 1:]
    sigma = jnp.asarray(stddev, dtype=axis.dtype)

    integrated_mass = sigma * (
        _normal_cdf_antiderivative((output_upper - source_lower) / sigma)
        - _normal_cdf_antiderivative((output_upper - source_upper) / sigma)
        - _normal_cdf_antiderivative((output_lower - source_lower) / sigma)
        + _normal_cdf_antiderivative((output_lower - source_upper) / sigma)
    )
    # Roundoff in far-tail cancellation can produce tiny negative entries. The matrix
    # depends only on static detector coordinates, so clipping those does not alter any
    # fitted-physics tangent.
    integrated_mass = jnp.maximum(integrated_mass, 0)
    return integrated_mass / jnp.diff(edges)[:, None]


def _uniform_gaussian_bin_kernel(axis, stddev):
    r"""Return the exact Toeplitz response kernel for uniform physical bins.

    On a uniform axis, :func:`_gaussian_bin_response` depends only on the
    output-minus-source bin lag. Storing those ``2*N - 1`` lags instead of the
    dense ``N*N`` matrix keeps fine 1D spectral grids memory-linear while retaining
    the same analytic double-bin integral and finite-detector boundary behavior.
    """

    if stddev <= 0:
        raise ValueError(f"Gaussian standard deviation must be positive, got {stddev!r}.")

    axis = jnp.ravel(jnp.asarray(axis))
    if axis.size == 1:
        return jnp.ones((1,), dtype=axis.dtype)

    cell_width = jnp.abs((axis[-1] - axis[0]) / (axis.size - 1))
    lags = jnp.arange(-(axis.size - 1), axis.size, dtype=axis.dtype) * cell_width
    sigma = jnp.asarray(stddev, dtype=axis.dtype)
    integrated_mass = sigma * (
        _normal_cdf_antiderivative((lags + cell_width) / sigma)
        - 2 * _normal_cdf_antiderivative(lags / sigma)
        + _normal_cdf_antiderivative((lags - cell_width) / sigma)
    )
    return jnp.maximum(integrated_mass, 0) / cell_width


def _apply_uniform_gaussian_bin_response(axis, values, stddev, *, response_axis):
    """Apply the exact uniform-bin Gaussian response without a dense matrix.

    Spectral axes in the forward model are generated by ``linspace`` and are therefore
    uniform. For modest grids direct convolution avoids FFT overhead; fine legacy 1D
    grids use FFT convolution, reducing the response storage from quadratic to linear.
    """

    axis = jnp.ravel(jnp.asarray(axis))
    values = jnp.asarray(values)
    if values.shape[response_axis] != axis.size:
        raise ValueError(
            "Gaussian-response axis length must match the selected value dimension, "
            f"got {axis.size} and {values.shape[response_axis]}."
        )

    kernel = _uniform_gaussian_bin_kernel(axis, stddev=stddev)
    moved = jnp.moveaxis(values, response_axis, -1)
    flat = moved.reshape((-1, axis.size))
    convolve = fftconvolve if axis.size > 2048 else jnp.convolve
    blurred = vmap(lambda row: convolve(row, kernel, mode="valid"))(flat)
    blurred = blurred.reshape(moved.shape)
    return jnp.moveaxis(blurred, -1, response_axis)


@dataclass(frozen=True)
class SpectrometerIRF:
    """Response of a 1D spectrometer: physical spectral blur, then pixel reduction.

    Every field is required. There are no defaults on purpose: a default for
    ``n_spectral_pixels`` would be silently correct on OMEGA and silently wrong
    elsewhere, which is the failure mode this module exists to prevent.

    This carries only *static* configuration, so it is an ordinary dataclass rather than
    an ``equinox`` module -- nothing here is a traced JAX leaf. The fitted instrument
    nuisance parameters (``amp1``/``amp2``/``amp3``) still arrive separately via the
    parameter tree.

    Args:
        spect_stddev: Gaussian spectral IRF standard deviation, in nm. A falsy value
            means "no spectral IRF" and the convolution is skipped (ion channel only).
        n_spectral_pixels: Number of wavelength pixels on the detector. The convolved
            spectrum is computed on a fine grid and averaged down onto this many bins.
        normalize: Normalization mode. ``0`` scales the spectrum to the measured data
            amplitude; ``> 0`` normalizes each wing to unity and scales it by the fitted
            ``amp1``/``amp2``.
    """

    spect_stddev: float
    n_spectral_pixels: int
    normalize: int


@dataclass(frozen=True, eq=False)
class AngularIRF:
    """Response of a 2D angularly-resolved detector: separable blur in wavelength and angle.

    ``eq=False`` because ``ang_axis`` is an array, and elementwise comparison would make
    a generated ``__eq__`` raise rather than return a bool.

    Args:
        spect_stddev: Gaussian spectral IRF standard deviation, in nm.
        ang_stddev: Gaussian angular IRF standard deviation, in degrees.
        ang_axis: Calibrated angular axis of the detector, in degrees.
        normalize: Normalization mode, as for :class:`SpectrometerIRF`.
    """

    spect_stddev: float
    ang_stddev: float
    ang_axis: np.ndarray
    normalize: int


def add_ATS_IRF(
    irf: AngularIRF, lamAxisE, modlE, TSins, *, apply_spectral_blur: bool = True
) -> Tuple[jnp.ndarray, jnp.ndarray]:
    """
    Applies a separable 2D Gaussian detector response to angular Thomson scattering data.
    The response is integrated over physical wavelength and angular cells rather than
    sampled in array-index space. The resulting spectrum is optionally normalized
    according to the IRF description.
    Args:
        irf (AngularIRF): Description of the angular detector's response.
        lamAxisE (jnp.ndarray): Array of wavelengths (in nm) at which the spectrum is computed.
        modlE (jnp.ndarray): Synthetic spectra produced by the formfactor routine, shape (n_angles, n_wavelengths).
        TSins (dict): Dictionary of Thomson scattering instrument parameters and their values.
        apply_spectral_blur: Whether to blur along wavelength. Set this to
            ``False`` when an upstream detector-bin quadrature has already folded in
            the spectral IRF; the angular IRF is still applied.
    Returns:
        lamAxisE (jnp.ndarray): Wavelength axis (in nm).
        ThryE (jnp.ndarray): Smoothed and optionally normalized synthetic spectra, shape (n_angles, n_wavelengths).
    """

    stddev_lam = irf.spect_stddev
    stddev_ang = irf.ang_stddev
    angular_response = _gaussian_bin_response(irf.ang_axis, stddev_ang)
    # The response matrices act on detector-bin mean densities. Matrix multiplication
    # applies every wavelength/angle column in one compiled operation.
    ThryE = angular_response @ modlE
    if apply_spectral_blur:
        ThryE = _apply_uniform_gaussian_bin_response(
            lamAxisE,
            ThryE,
            stddev_lam,
            response_axis=1,
        )

    if irf.normalize > 0:
        ThryE = jnp.where(
            lamAxisE < TSins["general"]["lam"],
            TSins["general"]["amp1"] * (ThryE / jnp.amax(ThryE[lamAxisE < TSins["general"]["lam"]])),
            TSins["general"]["amp2"] * (ThryE / jnp.amax(ThryE[lamAxisE > TSins["general"]["lam"]])),
        )
    return lamAxisE, ThryE


def add_ion_IRF(irf: SpectrometerIRF, lamAxisI, modlI, amps, TSins) -> Tuple[jnp.ndarray, jnp.ndarray]:
    """
    Applies an instrumental response function (IRF) to the ion spectral model and optionally normalizes the result.
    Parameters:
        irf (SpectrometerIRF): Description of the ion spectrometer's response.
        lamAxisI (jnp.ndarray): Wavelength axis for the ion spectrum.
        modlI (jnp.ndarray): Theoretical ion spectrum model to which the IRF will be applied.
        amps (float or jnp.ndarray): Amplitude scaling factor(s) for the spectrum.
        TSins (dict): Dictionary containing additional scaling parameters, specifically 'general' -> 'amp3'.
    Returns:
        lamAxisI (jnp.ndarray): The wavelength axis, possibly averaged over batches if the IRF is applied.
        ThryI (jnp.ndarray): The processed ion spectrum after convolution with the IRF and optional normalization.
    """

    stddevI = irf.spect_stddev
    if stddevI:
        ThryI = _apply_uniform_gaussian_bin_response(
            lamAxisI,
            modlI,
            stddevI,
            response_axis=0,
        )
        ThryI = jnp.average(ThryI.reshape(irf.n_spectral_pixels, -1), axis=1)
        #print(f"modlI max {jnp.max(modlI)}")
        #print(f"ThryI max {jnp.max(ThryI)}")
        #print(f"amps max {jnp.max(amps)}")

        if irf.normalize == 0:
            lamAxisI = jnp.average(lamAxisI.reshape(irf.n_spectral_pixels, -1), axis=1)
            ThryI = TSins["general"]["amp3"] * amps * ThryI / jnp.amax(ThryI)
            # lamAxisE = jnp.average(lamAxisE.reshape(irf.n_spectral_pixels, -1), axis=1)
    else:
        ThryI = modlI

    #print(f"final ThryI max {jnp.max(ThryI)}")
    return lamAxisI, ThryI


def add_electron_IRF(irf: SpectrometerIRF, lamAxisE, modlE, amps, TSins) -> Tuple[jnp.ndarray, jnp.ndarray]:
    """
    Applies an instrumental response function (IRF) to an electron model spectrum and normalizes the result.
    This function convolves the input electron model spectrum (`modlE`) with a Gaussian IRF defined by the IRF
    description, normalizes the convolved spectrum according to that description and the signal parameters, and
    optionally averages and rescales the output based on normalization settings.
    Args:
        irf (SpectrometerIRF): Description of the electron spectrometer's response.
        lamAxisE (jnp.ndarray): Wavelength axis for the electron spectrum.
        modlE (jnp.ndarray): Model electron spectrum to which the IRF will be applied.
        amps (float or jnp.ndarray): Amplitude scaling factor(s) for the output spectrum.
        TSins (dict): Dictionary containing signal parameters, including normalization wavelengths and amplitudes.
    Returns:
        lamAxisE (jnp.ndarray): The wavelength axis, possibly averaged over batches if the IRF is applied.
        ThryE (jnp.ndarray): The processed electron spectrum after convolution with the IRF and optional normalization.
        Tuple[jnp.ndarray, jnp.ndarray]: Tuple containing the (possibly averaged) wavelength axis and the processed, normalized electron spectrum.
    """

    stddevE = irf.spect_stddev
    ThryE = _apply_uniform_gaussian_bin_response(
        lamAxisE,
        modlE,
        stddevE,
        response_axis=0,
    )

    if irf.normalize > 0:
        ThryE = jnp.where(
            lamAxisE < TSins["general"]["lam"],
            TSins["general"]["amp1"] * (ThryE / jnp.amax(ThryE[lamAxisE < TSins["general"]["lam"]])),
            TSins["general"]["amp2"] * (ThryE / jnp.amax(ThryE[lamAxisE > TSins["general"]["lam"]])),
        )

    ThryE = jnp.average(ThryE.reshape(irf.n_spectral_pixels, -1), axis=1)
    if irf.normalize == 0:
        lamAxisE = jnp.average(lamAxisE.reshape(irf.n_spectral_pixels, -1), axis=1)
        ThryE = amps * ThryE / jnp.amax(ThryE)
        ThryE = jnp.where(
            lamAxisE < TSins["general"]["lam"], TSins["general"]["amp1"] * ThryE, TSins["general"]["amp2"] * ThryE
        )

    return lamAxisE, ThryE
