data:
  background:
    slice: 605
    type: fit
  fit_rng:
    blue_max: 496
    blue_min: 453
    iaw_cf_max: 526.8
    iaw_cf_min: 526.4
    iaw_max: 527.3
    iaw_min: 526.1
    red_max: 625
    red_min: 565
  lineouts:
    end: -275
    skip: 5
    start: -375
    type: um
  shotnum: 102727
mlflow:
  experiment: julie-inverse-thomson-scattering
  run: EPW 102727 skip 15 ne & te gradient = 5 not active
other:
  PhysParams:
    widIRF:
      ang_FWHM_ele: 1.0
      spect_FWHM_ele: 0.9
      spect_stddev_ele: 0.1
      spect_stddev_ion: 0.015
  calc_sigmas: false
  extraoptions:
    fit_EPWb: true
    fit_EPWr: true
    fit_IAW: true
    load_ele_spec: true
    load_ion_spec: true
  refit: false
  refit_thresh: 100
parameters:
  general:
    Te_gradient:
      active: false
      lb: 0.0
      num_grad_points: 10
      ub: 10.0
      val: 0.0
    Va:
      active: true
      angle: 0.0
      lb: -20.0
      ub: 12.0
      val: -4.7
    amp1:
      active: true
      lb: 0.01
      ub: 3.75
      val: 0.8
    amp2:
      active: true
      lb: 0.01
      ub: 1.2
      val: 0.45
    amp3:
      active: true
      lb: 0.0
      ub: 1.5
      val: 0.99
    lam:
      active: false
      lb: 525.5
      ub: 527.0
      val: 526.5
    ne_gradient:
      active: true
      lb: 0.0
      num_grad_points: 10
      ub: 9.0
      val: 4.0
    type:
      active: false
      general: null
    ud:
      active: true
      angle: 0.0
      lb: -20.0
      ub: 35.0
      val: 21.1
  species1:
    Te:
      active: true
      lb: 0.01
      ub: 0.9
      val: 0.41
    fe:
      active: false
      dim: 1
      fe_decrease_strict: false
      lb: -100.0
      length: 3999
      m_asym: 1.0
      m_theta: 0.0
      symmetric: false
      temp_asym: 1.0
      type:
        DLM: null
      ub: -0.5
      v_res: 0.05
      val: []
    m:
      active: false
      intens: 2.0
      lb: 2.0
      matte: false
      ub: 5.0
      val: 2.0
    ne:
      active: true
      lb: 0.01
      ub: 0.7
      val: 0.47
    type:
      active: false
      electron: null
  species2:
    A:
      active: false
      val: 1.0
    Ti:
      active: true
      lb: 0.0
      same: false
      ub: 0.4
      val: 0.053
    Z:
      active: false
      lb: 0.0
      ub: 1.0
      val: 1.0
    fract:
      active: false
      val: 1.0
    type:
      active: false
      data: null
      ion: null