data:
  background:
    slice: 800
    type: pixel
  lineouts:
    end: 2400
    skip: 50
    start: 1500
    type: ps
  shot_rot: 90.0
  shotnum: 116768
machine: gpu
mlflow:
  experiment: shot_day_10_22_25
  run: shot 116768
other:
  calc_sigmas: false
  extraoptions:
    fit_EPWb: true
    fit_EPWr: true
    fit_IAW: true
    load_ele_spec: true
    load_ion_spec: true
    spectype: angular
  include_gains: false
  refit: false
  refit_thresh: 5.0
parameters:
  electron:
    Te:
      active: true
      gradient_scalar: 10.0
      lb: 0.01
      ub: 2.0
      val: 1.0
    fe:
      active: false
      dim: 1
      nvx: 128
      params:
        Nl: 1
        dtx: 0.002
        dty: 0.0005
        flm_type: arbitrary
        init_m: 3.0
        learn_log: true
        m:
          lb: 2.0
          ub: 5.0
          val: 2.0
          matte: false
          intens: 2.0
        nvr: 128
        smooth: true
        window:
          len: 45
          sampling: 30
          type: hanning
      type: dlm
    ne:
      active: true
      gradient_scalar: 10.0
      lb: 0.03
      ub: 3.0
      val: 1.1
  general:
    Te_gradient:
      active: false
      lb: 0.0
      num_grad_points: 1
      ub: 10.0
      val: 0.0
    Va:
      active: true
      angle: 0.0
      lb: -40.5
      ub: 40.5
      val: 1.766
    amp1:
      active: true
      lb: 0.20
      ub: 3.75
      val: 1.0
    amp2:
      active: true
      lb: 0.20
      ub: 3.75
      val: 1.0
    amp3:
      active: true
      lb: 0.01
      ub: 3.75
      val: 1.0
    lam:
      active: false
      lb: 524.0
      ub: 529.0
      val: 526.5
    ne_gradient:
      active: false
      lb: 0.0
      num_grad_points: 1
      ub: 15.0
      val: 0.0
    ud:
      active: false
      angle: 0.0
      lb: -100.0
      ub: 100.0
      val: 0.0
  ion-1:
    A:
      active: false
      val: 40.0
    Ti:
      active: true
      lb: 0.01
      same: false
      ub: 1.0
      val: 0.1594
    Z:
      active: true
      lb: 6.0
      ub: 18.0
      val: 15.0
    fract:
      active: false
      val: 0.11
  ion-2:
    A:
      active: false
      val: 1.0
    Ti:
      active: false
      lb: 0.01
      same: true
      ub: 1.0
      val: 0.12
    Z:
      active: false
      lb: 0.5
      ub: 1.5
      val: 1.0
    fract:
      active: false
      val: 0.89
