data:
  background:
    slice: 500
    type: fit
  lineouts:
        type:
            um
        start: -900
        end: 800
        skip: 50
  shotnum: 92535

machine: gpu

mlflow:
  experiment: Kinshock19A
  run: 92535-19

other:
  calc_sigmas: false
  extraoptions:
    fit_EPWb: true
    fit_EPWr: true
    fit_IAW: true
    load_ele_spec: true
    load_ion_spec: true
  refit: false
  refit_thresh: 20.0

parameters:
  electron:
    Te:
      active: True
      lb: 0.01
      ub: 0.7
      val: 0.2
    fe:
      active: false
      dim: 1
      nvx: 320
      params:
        m:
          lb: 2.0
          ub: 5.0
          val: 2.0
          matte: false
          intens: 2.5
      type: dlm
    ne:
      active: true
      lb: 0.05
      ub: 0.5
      val: 0.25
  general:
    Te_gradient:
      active: false
      lb: 0.0
      num_grad_points: 1
      ub: 15.0
      val: 0.0
    amp1:
      active: true
      lb: 0.01
      ub: 3.75
      val: 1.0
    amp2:
      active: true
      lb: 0.01
      ub: 3.75
      val: 1.0
    amp3:
      active: true
      lb: 0.01
      ub: 3.75
      val: 1.0
    lam:
      active: false
      lb: 524.0
      ub: 528.0
      val: 526.5
    ne_gradient:
      active: false
      lb: 0.0
      num_grad_points: 1
      ub: 15.0
      val: 0.0
    ud:
      active: true 
      angle: 0.0
      lb: -10.0
      ub: 10.0
      val: 0.0

  ion-1:
    A:
      active: false
      val: 1.0
    Ti:
      active: True
      lb: 0.01
      same: false
      ub: 1.2
      val: 0.5
    Z:
      active: false
      lb: 1.0
      ub: 18.0
      val: 1.0
    Va:
      active: True
      angle: 0.0
      lb: 0.0
      ub: 45.0
      val: 20.0
    fract:
      active: True
      lb: 0.1
      ub: 1.0
      val: 0.6
    type:
      active: false
      ion: null 

  ion-2:
    A:
      active: false
      val: 4.0
    Ti:
      active: True
      lb: 0.01
      same: false
      ub: 1.0
      val: 0.1
    Z:
      active: false
      lb: 1.0
      ub: 2.0
      val: 1.990
    Va:
      active: True
      angle: 0.0
      lb: 0.0
      ub: 30.0
      val: 10.0
    fract:
      active: True
      lb: 0.01
      ub: 1.0
      val: 0.4
    type:
      active: false
      ion: null