data:
  fit_EPWb: true
  fit_EPWr: true
  fit_IAW: true
  load_ele_spec: true
  load_ion_spec: true
  background:
    slice: 800
    type: pixel
  lineouts:
    end: 300
    skip: 25
    start: 2400
    type: ps
  shotnum: 116774

machine: gpu

mlflow:
  experiment: shot_day_10_22_25
  run: s116774-revisit-nantest

other:
  Ipump_14: 1.58
  beam_diam_um: 100
  calc_sigmas: false
  include_gains: false
  refit: false
  refit_thresh: 5.0

parameters:
  electron:
    Te:
      active: true
      lb: 0.01
      ub: 2.0
      val: 0.7
    fe:
      active: false
      dim: 1
      nvx: 320
      params:
        m:
          intens: 6.5
          lb: 1.9
          matte: true
          ub: 5.0
          val: 2.5
      type: dlm
    ne:
      active: true
      lb: 0.03
      ub: 2.0
      val: 0.6
  general:
    Te_gradient:
      active: false
      lb: 0.0
      num_grad_points: 1
      ub: 10.0
      val: 0.0
    amp1:
      active: true
      lb: 0.01
      ub: 3.75
      val: 1.0
    amp2:
      active: true
      lb: 0.01
      ub: 3.75
      val: 1.0
    amp3:
      active: true
      lb: 0.01
      ub: 3.75
      val: 1.0
    brem_amp:
      active: false
      lb: 0.0
      ub: 1.0
      val: 0.4
    brem_c:
      active: false
      lb: 0.0
      ub: 1.0
      val: 0.4
    lam:
      active: true
      lb: 526.0
      ub: 527.0
      val: 526.5
    ne_gradient:
      active: false
      lb: 0.0
      num_grad_points: 1
      ub: 15.0
      val: 0.0
    ud:
      active: true
      angle: 0.0
      lb: -20.0
      ub: 20.0
      val: 0.0
  
  ion-1:
    A:
      active: false
      val: 83.8
    Ti:
      active: true
      lb: 0.01
      same: false
      ub: 2.0
      val: 0.3
    Va:
      active: true
      angle: 0.0
      lb: -20.5
      ub: 20.5
      val: -2.0
    Z:
      active: true
      lb: 6.0
      ub: 26.1
      val: 25.9
    fract:
      active: false
      val: 1.0
