parameters:
    species1:
        type:
            electron:
            active: False
        Te:
            val: 0.33
            active: True
            lb: 0.05
            ub: 1.2
        ne:
            val: 0.15
            active: false
            lb: 0.01
            ub: 0.75
        m:
            val: 2.0
            active: false
            lb: 2.0
            ub: 5.0
            matte: False
            intens: 2.0
        fe:
            val: [ ]
            active: False
            length: 3999
            type:
                DLM:
            lb: -100.
            ub: -0.5
            fe_decrease_strict: False
            symmetric: False
            dim: 1
            v_res: 0.05
            temp_asym: 1.0
            m_theta: 0.0
            m_asym: 1.

    species2:
        type:
            ion:
            active: False
        Ti:
            val: 0.1
            active: true
            same: False
            lb: 0.01
            ub: 1.0
        Z:
            val: 16.0
            active: true
            lb: 1.0
            ub: 18.0
        A:
            val: 40.0
            active: False
        fract:
            val: 1.0
            active: False

    general:
        type:
            general:
            active: False
        amp1:
            val: 1.0
            active: false
            lb: 0.01
            ub: 3.75
        amp2:
            val: 1.0
            active: false
            lb: 0.01
            ub: 3.75
        amp3:
            val: 1.0
            active: true
            lb: 0.01
            ub: 3.75
        lam:
            val: 526.4
            active: false
            lb: 526.0
            ub: 527.0
        Te_gradient:
            val: 0.0
            active: false
            lb: 0.
            ub: 10.
            num_grad_points: 1
        ne_gradient:
            val: 0.
            active: False
            lb: 0.
            ub: 15.
            num_grad_points: 1
        ud:
            val: 0.0
            angle: 0.0
            active: true
            lb: -10.0
            ub: 10.0
        Va:
            val: 0.0
            angle: 0.0
            active: true
            lb: -10.0
            ub: 10.0
        blur:
            val: []
            active: False
            lb: 0.
            ub: 10.
        specCurvature:
            val: []
            active: False
            lb: .1
            ub: 10.
        fitprops:
            val: []
            active: False

other:
    crop_window: 256
    ion_window_start: 525
    ion_window_end: 528
    ele_window_start: 425
    ele_window_end: 625
    BinWidth: 10
    NumBinInRng: 0
    TotalNumBin: 1023
    expandedions: False
    extraoptions:
        load_ion_spec: False
        load_ele_spec: True
        fit_IAW: False
        fit_EPWb: True
        fit_EPWr: True
    PhysParams:
        background: [0, 0]
        norm: 0
    iawoff: 0
    iawfilter: [1, 4, 24, 528]
    CCDsize: [1024, 1024]
    flatbg: 0
    gain: 1
    points_per_pixel: 5
    ang_res_unit: 10
    lam_res_unit: 5
    refit: False
    refit_thresh: 0.25
    calc_sigmas: False

data:
    shotnum: 101675
    shotDay: False
    launch_data_visualizer: True
    fit_rng:
        blue_min: 450
        blue_max: 510
        red_min: 545
        red_max: 650
        iaw_min: 525
        iaw_max: 528
        iaw_cf_min: 526.4
        iaw_cf_max: 526.6
        forward_epw_start: 400
        forward_epw_end: 700
        forward_iaw_start: 525.5
        forward_iaw_end: 527.5
    bgscaleE: 1.0
    bgscaleI: 0.1
    bgshotmult: 1
    ion_loss_scale: 1.0
    ele_t0: 0
    ion_t0_shift: 0.0
    ele_lam_shift: 0.0
    probe_beam: P9
    dpixel: 3
    lineouts:
        type:
            pixel
        start: 500
        end: 510
        skip: 1
    background:
        type:
            fit
        slice: 900
    probe_beam: P9

plotting:
    n_sigmas: 3
    rolling_std_width: 5
    data_cbar_u: data
    data_cbar_l: 0

optimizer:
    # use adam for nn / stochastic gradient descent
    # use L-BFGS-B for full batch / parameter learning
    # although adam will work here too
    method: adam #l-bfgs-b
    hessian: False
    y_norm: True
    x_norm: False
    grad_method: AD
    batch_size: 4
    num_epochs: 1
    learning_rate: 1.0e-4
    parameter_norm: True
    refine_factor: 0
    num_mins: 8
    sequential: True

nn:
    use: false
    conv_filters: 32|32|16
    linear_widths: 16|8

dist_fit:
    window:
        len: 0.2 #should be even
        type: hamming # one of [hamming, hann, bartlett]

mlflow:
    experiment: inverse-thomson-scattering
    run: base
