name: tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-tsadar-cpu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: astral-sh/setup-uv@v3
      - name: Install HDF4 system library
        run: sudo apt-get update && sudo apt-get install -y libhdf4-dev
      - name: Install tsadar (CPU)
        run: uv pip install --system -e ".[test,hdf]"
      - name: Run tests
        run: pytest tests/ -m "not slow"

  test-tsadar-gpu:
    runs-on: "gpu_runner"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: astral-sh/setup-uv@v3
      - name: Install HDF4 system library
        run: sudo apt-get update && sudo apt-get install -y libhdf4-dev
      - name: Install tsadar (GPU)
        run: uv pip install --system -e ".[gpu,test,hdf]"
      - name: Run tests
        run: pytest tests/ -m "not slow"
